extends: eslint:recommended

globals:
  $: false
  jQuery: false

rules:
  # Possible Errors
  "no-extra-parens": 2
  "no-unsafe-finally": 2
  "valid-jsdoc": 2

  # Best Practices
  "accessor-pairs": 2
  "array-callback-return": 2
  "block-scoped-var": 0
  "complexity": 0
  "consistent-return": 0
  "curly": 2
  "default-case": 0
  "dot-location": [2, "property"]
  "dot-notation": 0
  "eqeqeq": [0, "allow-null"]
  "guard-for-in": 2
  "no-alert": 0
  "no-caller": 2
  "no-div-regex": 2
  "no-else-return": 0
  "no-empty-function": 2
  "no-eq-null": 0
  "no-eval": 2
  "no-extend-native": 2
  "no-extra-bind": 2
  "no-extra-label": 2
  "no-floating-decimal": 2
  "no-implicit-coercion": [2, { "allow": ["!!", "~"] }]
  "no-implicit-globals": 0
  "no-implied-eval": 2
  "no-invalid-this": 0
  "no-iterator": 2
  "no-labels": [2, {"allowLoop": true, "allowSwitch": true}]
  "no-lone-blocks": 2
  "no-loop-func": 2
  "no-magic-numbers": 0
  "no-multi-str": 2
  "no-native-reassign": 2
  "no-new": 2
  "no-new-func": 2
  "no-new-wrappers": 2
  "no-octal": 2
  "no-octal-escape": 2
  "no-param-reassign": 2
  "no-proto": 2
  "no-redeclare": 0
  "no-return-assign": 2
  "no-script-url": 2
  "no-self-compare": 2
  "no-sequences": 2
  "no-throw-literal": 2
  "no-unmodified-loop-condition": 2
  "no-unused-expressions": 2
  "no-useless-call": 2
  "no-useless-concat": 2
  "no-useless-escape": 0
  "no-void": 2
  "no-warning-comments": [1, { "terms": ["todo", "fixme", "hack"] }]
  "no-with": 2
  "radix": 0
  "vars-on-top": 0
  "wrap-iife": 2
  "yoda": [2, "never", { "exceptRange": true }]

  # Strict
  "strict": 0

  # Variables
  "init-declarations": 0
  "no-catch-shadow": 2
  "no-label-var": 2
  "no-restricted-globals": 2
  "no-shadow": 0
  "no-shadow-restricted-names": 2
  "no-undef": 0
  "no-undef-init": 2
  "no-undefined": 0
  "no-unused-vars": 0
  "no-use-before-define": 0

  # Stylistic Issues
  "array-bracket-spacing": 2
  "block-spacing": 2
  "brace-style": [2, "1tbs", { "allowSingleLine": true }]
  "camelcase": 0
  "comma-spacing": [2, { "before": false, "after": true }]
  "comma-style": [2, "last"]
  "computed-property-spacing": 2
  "consistent-this": [0, "self"]
  "eol-last": 2
  "func-names": 0
  "func-style": 0
  "id-blacklist": 2
  "id-length": 0
  "id-match": 2
  "indent": [2, 2, {"VariableDeclarator": { "var": 2, "let": 2, "const": 3 }, "SwitchCase": 1 }]
  "jsx-quotes": 2
  "key-spacing": [2, { "beforeColon": false, "afterColon": true, "mode": "minimum" }]
  "keyword-spacing": 2
  "linebreak-style": 2
  "lines-around-comment": 0
  "max-depth": 2
  "max-len": 0
  "max-nested-callbacks": 2
  "max-params": 0
  "max-statements": 0
  "max-statements-per-line": 0
  "new-cap": 0
  "new-parens": 2
  "newline-after-var": 0
  "newline-before-return": 0
  "newline-per-chained-call": [2, {"ignoreChainWithDepth": 5}]
  "no-array-constructor": 2
  "no-bitwise": 2
  "no-continue": 2
  "no-inline-comments": 0
  "no-lonely-if": 2
  "no-mixed-spaces-and-tabs": 2
  "no-multiple-empty-lines": [2, { "max": 2 }]
  "no-negated-condition": 2
  "no-nested-ternary": 2
  "no-new-object": 2
  "no-plusplus": 0
  "no-restricted-syntax": 2
  "no-spaced-func": 2
  "no-ternary": 0
  "no-trailing-spaces": 2
  "no-underscore-dangle": 0
  "no-unneeded-ternary": 2
  "no-whitespace-before-property": 2
  "one-var": 0
  "one-var-declaration-per-line": 2
  "operator-assignment": [2, "always"]
  "operator-linebreak": 2
  "padded-blocks": [2, "never"]
  "quote-props": [2, "consistent", { "keywords": true }]
  "quotes": [0, "single", "avoid-escape"]
  "require-jsdoc": 0
  "semi": [2, "always"]
  "semi-spacing": 2
  "sort-vars": 0
  "space-before-blocks": [2, "always"]
  "space-before-function-paren": [2, "never"]
  "space-in-parens": [2, "never"]
  "space-infix-ops": 2
  "space-unary-ops": [2, { "words": true, "nonwords": false }]
  "spaced-comment": [2, "always", { "line": { "markers": ["="], "exceptions": ["/", "-"] } }]
  "wrap-regex": 2
